### ISSUE TITLE
Can I use netlink to modify rule/route in my own kernel module? How?

### ISSUE THREAD

**Issue by sjc2870** [mwarning/netlink-examples#2]
I'm not a net module developer, I wander that can I use netlink mechanism to modify rule/route in my own kernel module?
Just like the following command does
 `ip route add to 192.168.11.11 table 20` or
 `ip route delete to 192.168.11.11 `

I looked up some sources, most of which are analyzing the communication between the kernel level and the user level, and related codes are little in kernel.  I just know how to use `netlink_kernel_create` to create socket in kernel, but don't know how to modify route at all. Do you have any suggested sources or information or something?
Looking forward for your reply!

**Comment by mwarning** [comment]
I haven't done that either.
But you should find what you need in `kernel_netlink.c` here https://www.irif.fr/~jch/software/babel/#download
